const {Plugin,ItemView,TextFileView,PluginSettingTab,Setting,TFile,MarkdownRenderer,Notice,setIcon}=require("obsidian");
const fs=require("fs"),path=require("path"),os=require("os");
const VS="agent-trace-sessions",VT="agent-trace-view",VJ="agent-trace-json",EXT=["json","jsonl","ndjson"],SMART=300,MDMAX=250000,JLIM=1000;
const DEF={codexSessionsPath:path.join(os.homedir(),".codex","sessions"),maxSessions:300,compactConversation:true};
class P extends Plugin{
 async onload(){this.settings={...DEF,...((await this.loadData())||{})};this.registerView(VS,l=>new Sessions(l,this));this.registerView(VT,l=>new Trace(l,this));this.registerView(VJ,l=>new JsonView(l));this.registerExtensions(EXT,VJ);this.addRibbonIcon("messages-square","Agent trace sessions",()=>this.openSessions());this.addCommand({id:"open-agent-trace-sessions",name:"Open agent trace sessions",callback:()=>this.openSessions()});this.addSettingTab(new Settings(this.app,this))}
 async save(){await this.saveData(this.settings)}
 async openSessions(){let l=this.app.workspace.getLeavesOfType(VS)[0]||this.app.workspace.getLeaf("tab");await l.setViewState({type:VS,active:true});this.app.workspace.revealLeaf(l)}
 async openTrace(filePath){const l=this.app.workspace.getLeaf("tab");await l.setViewState({type:VT,active:true,state:{filePath}});this.app.workspace.revealLeaf(l)}
}
module.exports=P;
class Settings extends PluginSettingTab{
 constructor(app,p){super(app,p);this.p=p}
 display(){const e=this.containerEl;e.empty();e.createEl("h2",{text:"Agent Trace Reader"});
 new Setting(e).setName("Codex sessions folder").setDesc("Default: ~/.codex/sessions. Read-only; nothing is copied into the vault.").addText(t=>t.setValue(this.p.settings.codexSessionsPath).onChange(async v=>{this.p.settings.codexSessionsPath=home(v.trim());await this.p.save()}));
 new Setting(e).setName("Maximum sessions").addText(t=>t.setValue(String(this.p.settings.maxSessions)).onChange(async v=>{const n=parseInt(v,10);if(n>0){this.p.settings.maxSessions=Math.min(n,5000);await this.p.save()}}));
 new Setting(e).setName("Compact conversation").setDesc("Collapse system/tool/reasoning traffic into Process blocks.").addToggle(t=>t.setValue(this.p.settings.compactConversation).onChange(async v=>{this.p.settings.compactConversation=v;await this.p.save()}))}
}
class Sessions extends ItemView{
 constructor(l,p){super(l);this.p=p}getViewType(){return VS}getDisplayText(){return"Agent sessions"}getIcon(){return"messages-square"}async onOpen(){await this.render()}
 async render(){const r=this.contentEl;r.empty();r.addClass("atr-sessions");const h=r.createDiv({cls:"atr-header"}),x=h.createDiv();x.createEl("h2",{text:"Agent Sessions"});x.createDiv({cls:"atr-muted",text:"Codex · local, read-only"});const b=btn(h,"refresh-cw","Refresh");b.onclick=()=>this.render();const root=home(this.p.settings.codexSessionsPath);r.createDiv({cls:"atr-source",text:root});if(!dir(root)){r.createDiv({cls:"atr-empty-card",text:"Codex sessions folder not found. Set it in Settings → Agent Trace Reader."});return}let ss;try{ss=scan(root,this.p.settings.maxSessions)}catch(e){r.createDiv({cls:"atr-error",text:"Scan failed: "+err(e)});return}if(!ss.length){r.createDiv({cls:"atr-empty-card",text:"No rollout-*.jsonl files found."});return}for(const [label,items] of groups(ss)){const sec=r.createDiv({cls:"atr-session-section"});sec.createEl("h3",{text:label});for(const s of items){const c=sec.createEl("button",{cls:"atr-session-card",attr:{type:"button"}}),title=s.title||basename(s.cwd)||s.fileName;c.createDiv({cls:"atr-session-title",text:title});const m=c.createDiv({cls:"atr-session-meta"});m.createSpan({text:fmt(s.modifiedMs)});if(s.cwd)m.createSpan({text:s.cwd});if(s.sessionId)m.createSpan({text:short(s.sessionId)});c.onclick=()=>this.p.openTrace(s.filePath)}}}
}
class Trace extends ItemView{
 constructor(l,p){super(l);this.p=p;this.filePath="";this.tab="conversation";this.raw="";this.parsed=null}getViewType(){return VT}getDisplayText(){return this.parsed?.title||basename(this.filePath)||"Agent trace"}getIcon(){return"messages-square"}
 async setState(s,res){await super.setState(s,res);this.filePath=s&&typeof s.filePath==="string"?s.filePath:"";await this.load()}getState(){return{filePath:this.filePath}}async onOpen(){if(this.filePath)await this.load()}
 async load(){try{this.raw=fs.readFileSync(this.filePath,"utf8");this.parsed=parseTrace(this.raw);this.render()}catch(e){this.contentEl.empty();this.contentEl.createDiv({cls:"atr-error",text:"Could not read trace: "+err(e)})}}
 render(){const r=this.contentEl;r.empty();r.addClass("atr-trace");const p=this.parsed;if(!p)return;const h=r.createDiv({cls:"atr-trace-header"}),left=h.createDiv({cls:"atr-trace-heading"});left.createEl("h2",{text:p.title||basename(this.filePath)});const meta=left.createDiv({cls:"atr-trace-meta"});if(p.cwd)meta.createSpan({text:p.cwd});if(p.sessionId)meta.createSpan({text:short(p.sessionId)});const tabs=h.createDiv({cls:"atr-tabs"});for(const t of["conversation","trajectory","raw"]){const b=tabs.createEl("button",{cls:"atr-tab"+(this.tab===t?" is-active":""),text:cap(t)});b.onclick=()=>{this.tab=t;this.render()}}if(p.errors.length)r.createDiv({cls:"atr-warning",text:p.errors.length+" malformed JSONL line(s); Raw remains available."});const body=r.createDiv({cls:"atr-trace-body"});if(this.tab==="conversation")this.convo(body,p.events);else if(this.tab==="trajectory")this.traj(body,p.events);else rawView(body,this.raw)}
 convo(parent,events){const use=events.filter(e=>["user","assistant","system","tool-call","tool-result","reasoning"].includes(e.kind));if(!use.length){parent.createDiv({cls:"atr-empty-card",text:"No conversation events recognized. Use Trajectory or Raw."});return}let proc=[];const flush=()=>{if(!proc.length)return;const d=parent.createEl("details",{cls:"atr-process"});if(!this.p.settings.compactConversation)d.open=true;d.createEl("summary",{text:`Process · ${proc.length} event${proc.length===1?"":"s"}`});proc.forEach(e=>card(d,e,this));proc=[]};for(const e of use){if(e.kind==="user"||e.kind==="assistant"){flush();card(parent,e,this)}else proc.push(e)}flush()}
 traj(parent,events){for(const e of events){const d=parent.createEl("details",{cls:"atr-trajectory-row atr-kind-"+e.kind}),s=d.createEl("summary");s.createSpan({cls:"atr-event-index",text:String(e.index+1).padStart(3,"0")});s.createSpan({cls:"atr-event-time",text:e.timestamp?time(e.timestamp):"—"});s.createSpan({cls:"atr-event-kind",text:e.kind});s.createSpan({cls:"atr-event-title",text:e.title});const c=d.createDiv({cls:"atr-event-details"});if(e.content)smart(c,e.content,this);jsonTree(c,e.raw,"raw",this)}}}
class JsonView extends TextFileView{
 getViewType(){return VJ}getDisplayText(){return this.file?.basename||"JSON viewer"}getIcon(){return"braces"}setViewData(d){this.data=d;this.render()}getViewData(){return this.data}clear(){this.data="";this.contentEl.empty()}
 render(){const r=this.contentEl;r.empty();r.addClass("atr-json");const h=r.createDiv({cls:"atr-header"});h.createEl("h2",{text:this.file?.name||"JSON"});const ext=this.file?.extension?.toLowerCase()||"json";if(ext==="jsonl"||ext==="ndjson"){const ls=this.data.split(/\r?\n/).filter(x=>x.trim());ls.slice(0,JLIM).forEach((line,i)=>{const d=r.createEl("details",{cls:"atr-json-record"});d.createEl("summary",{text:"line "+(i+1)});try{jsonTree(d,JSON.parse(line),"root",this)}catch{d.createEl("pre",{text:line})}});if(ls.length>JLIM)r.createDiv({cls:"atr-warning",text:(ls.length-JLIM)+" records hidden for performance."});return}try{jsonTree(r,JSON.parse(this.data),"root",this)}catch(e){r.createDiv({cls:"atr-error",text:"JSON parse error: "+err(e)});r.createEl("pre",{text:this.data})}}
}
function card(p,e,comp){const c=p.createDiv({cls:"atr-message atr-message-"+e.kind}),h=c.createDiv({cls:"atr-message-header"});h.createSpan({cls:"atr-message-role",text:(e.role||e.kind).toUpperCase()});if(e.timestamp)h.createSpan({cls:"atr-message-time",text:time(e.timestamp)});if(e.content){const b=c.createDiv({cls:"atr-message-body"});messageBody(b,e.content,comp)}else c.createDiv({cls:"atr-muted",text:e.title})}
function messageBody(p,v,comp){if(v.length<=MDMAX&&looksMd(v)){MarkdownRenderer.render(comp.app,v,p,"",comp).catch(()=>{p.empty();p.createDiv({cls:"atr-message-text",text:v})})}else p.createDiv({cls:"atr-message-text",text:v})}
function smart(p,v,comp){const d=p.createEl("details",{cls:"atr-smart-string"}),s=d.createEl("summary");s.createSpan({text:v.length.toLocaleString()+" chars"});const bar=d.createDiv({cls:"atr-smart-tabs"}),out=d.createDiv({cls:"atr-smart-content"}),j=tryJson(v),md=v.length<=MDMAX&&looksMd(v),modes=[...(md?["Rendered"]:[]),"Text","Raw",...(j!==null?["JSON"]:[])];let active=md?"Rendered":"Text",rendered=false;const render=m=>{active=m;rendered=true;bar.querySelectorAll("button").forEach(b=>b.toggleClass("is-active",b.textContent===m));out.empty();if(m==="Rendered"){MarkdownRenderer.render(comp.app,v,out,"",comp).catch(()=>{out.empty();out.createEl("pre",{cls:"atr-plain-text",text:v})})}else if(m==="Text")out.createEl("pre",{cls:"atr-plain-text",text:v});else if(m==="Raw")out.createEl("pre",{cls:"atr-plain-text",text:JSON.stringify(v)});else jsonTree(out,j,"root",comp)};for(const m of modes){const b=bar.createEl("button",{cls:"atr-mini-tab",text:m});b.onclick=e=>{e.preventDefault();e.stopPropagation();render(m)}}d.addEventListener("toggle",()=>{if(d.open&&!rendered)render(active)})}
function jsonTree(p,v,label,comp){if(Array.isArray(v)){const d=p.createEl("details",{cls:"atr-json-branch",attr:{open:""}});d.createEl("summary",{text:`${label}  [${v.length}]`});v.forEach((x,i)=>jsonTree(d,x,"["+i+"]",comp));return}if(obj(v)){const es=Object.entries(v),d=p.createEl("details",{cls:"atr-json-branch",attr:{open:""}});d.createEl("summary",{text:`${label}  {${es.length}}`});es.forEach(([k,x])=>jsonTree(d,x,k,comp));return}const row=p.createDiv({cls:"atr-json-leaf"});row.createSpan({cls:"atr-json-key",text:label});row.createSpan({cls:"atr-json-type",text:v===null?"null":typeof v});if(typeof v==="string"&&(v.length>=SMART||/\r?\n/.test(v))){const b=row.createDiv({cls:"atr-json-smart"});smart(b,v,comp)}else row.createSpan({cls:"atr-json-value",text:typeof v==="string"?v:JSON.stringify(v)})}
function parseTrace(raw){const events=[],errors=[];let sessionId,cwd,createdAt,title;raw.split(/\r?\n/).forEach((line,i)=>{if(!line.trim())return;let r;try{r=JSON.parse(line)}catch(e){errors.push({line:i+1,message:err(e)});return}const e=norm(r,events.length);events.push(e);if(r.type==="session_meta"&&obj(r.payload)){sessionId=str(r.payload.id)||sessionId;cwd=str(r.payload.cwd)||cwd;createdAt=str(r.timestamp)||str(r.payload.timestamp)||createdAt;title=str(r.payload.title)||title}if(!title&&e.kind==="user"&&e.content)title=titleOf(e.content)});return{events:dedupeMessages(events),errors,sessionId,cwd,createdAt,title}}
function norm(r,index){if(!obj(r))return{index,sourceType:"unknown",kind:"unknown",title:"Unknown",raw:r};const ts=str(r.timestamp),st=str(r.type)||"unknown",p=obj(r.payload)?r.payload:null;if(st==="session_meta")return{index,timestamp:ts,sourceType:st,kind:"metadata",title:"Session metadata",raw:r};if(st==="turn_context")return{index,timestamp:ts,sourceType:st,kind:"metadata",title:"Turn context",raw:r};if(st==="response_item"&&p)return resp(r,p,index,ts,st);if(st==="event_msg"&&p){const pt=str(p.type)||"event",text=extract(p);if(pt==="user_message")return{index,timestamp:ts,sourceType:st,kind:"user",role:"user",title:"User",content:text,raw:r};if(/reason|analysis/i.test(pt))return{index,timestamp:ts,sourceType:st,kind:"reasoning",title:pt,content:text,raw:r};return{index,timestamp:ts,sourceType:st,kind:"event",title:pt,content:text,raw:r}}return{index,timestamp:ts,sourceType:st,kind:"unknown",title:st,content:extract(r),raw:r}}
function resp(r,p,index,ts,st){const type=str(p.type)||"response_item",role=str(p.role),text=extract(p);if(type==="message"){const kind=role==="user"?"user":role==="assistant"?"assistant":role==="system"||role==="developer"?"system":"event";return{index,timestamp:ts,sourceType:st,kind,role,title:cap(role||"message"),content:text,raw:r}}if(/function_call_output|tool_output|custom_tool_call_output/i.test(type))return{index,timestamp:ts,sourceType:st,kind:"tool-result",title:str(p.name)||str(p.call_id)||"Tool result",content:text||str(p.output),raw:r};if(/function_call|tool_call|custom_tool_call/i.test(type)){const a=p.arguments??p.input??p.params;return{index,timestamp:ts,sourceType:st,kind:"tool-call",title:str(p.name)||str(p.tool_name)||"Tool call",content:typeof a==="string"?a:a!==undefined?JSON.stringify(a,null,2):text,raw:r}}if(/reason|analysis/i.test(type))return{index,timestamp:ts,sourceType:st,kind:"reasoning",title:"Reasoning",content:text,raw:r};return{index,timestamp:ts,sourceType:st,kind:"event",title:type,content:text,raw:r}}
function extract(v){if(typeof v==="string")return v;if(Array.isArray(v)){const a=v.map(extract).filter(Boolean);return a.length?a.join("\n\n"):undefined}if(!obj(v))return;for(const k of["text","message","content","output_text","input_text","output","summary"]){const x=extract(v[k]);if(x)return x}}
function scan(root,limit){const out=[],stack=[root];while(stack.length){const cur=stack.pop();let es;try{es=fs.readdirSync(cur,{withFileTypes:true})}catch{continue}for(const e of es){const f=path.join(cur,e.name);if(e.isDirectory())stack.push(f);else if(e.isFile()&&e.name.startsWith("rollout-")&&e.name.endsWith(".jsonl")){try{const st=fs.statSync(f);out.push({filePath:f,fileName:e.name,modifiedMs:st.mtimeMs})}catch{}}}}out.sort((a,b)=>b.modifiedMs-a.modifiedMs);return out.slice(0,limit).map(enrich)}
function enrich(s){try{const fd=fs.openSync(s.filePath,"r"),buf=Buffer.alloc(65536),n=fs.readSync(fd,buf,0,buf.length,0);fs.closeSync(fd);for(const line of buf.toString("utf8",0,n).split(/\r?\n/).slice(0,20)){let r;try{r=JSON.parse(line)}catch{continue}if(r.type==="session_meta"&&obj(r.payload)){s.sessionId=str(r.payload.id)||s.sessionId;s.cwd=str(r.payload.cwd)||s.cwd;s.createdAt=str(r.timestamp)||s.createdAt;s.title=str(r.payload.title)||s.title}const e=norm(r,0);if(!s.title&&e.kind==="user"&&e.content)s.title=titleOf(e.content)}}catch{}return s}
function groups(ss){const m=new Map;for(const s of ss){const k=day(s.modifiedMs);if(!m.has(k))m.set(k,[]);m.get(k).push(s)}return m}
function rawView(p,raw){const pre=p.createEl("pre",{cls:"atr-raw"});raw.split(/\r?\n/).forEach((line,i)=>{const r=pre.createDiv({cls:"atr-raw-line"});r.createSpan({cls:"atr-line-number",text:String(i+1)});r.createSpan({cls:"atr-line-content",text:line})})}
function btn(p,icon,label){const b=p.createEl("button",{cls:"clickable-icon atr-icon-button",attr:{title:label,"aria-label":label}});setIcon(b,icon);return b}
function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)}function str(v){return typeof v==="string"?v:undefined}function err(e){return e instanceof Error?e.message:String(e)}function home(v){return v==="~"?os.homedir():v.startsWith("~/")?path.join(os.homedir(),v.slice(2)):v}function dir(v){try{return fs.statSync(v).isDirectory()}catch{return false}}function basename(v){return v?path.basename(v):""}function short(v){return v.length>12?v.slice(0,8)+"…"+v.slice(-4):v}function cap(v){return v? v[0].toUpperCase()+v.slice(1):v}function titleOf(v){return v.replace(/\s+/g," ").trim().slice(0,80)||"Untitled session"}function fmt(ms){return new Date(ms).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}function time(v){const d=new Date(v);return isNaN(d)?String(v).slice(0,8):d.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit",second:"2-digit"})}function day(ms){const n=new Date(),t=new Date(ms),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime(),b=new Date(t.getFullYear(),t.getMonth(),t.getDate()).getTime(),d=Math.round((a-b)/86400000);return d===0?"Today":d===1?"Yesterday":d<7?"Earlier this week":t.toLocaleDateString(undefined,{year:"numeric",month:"long"})}function looksMd(v){return /(^|\n)#{1,6}\s|(^|\n)\s*[-*+]\s|\`\`\`|\[[^\]]+\]\([^\)]+\)|(^|\n)>\s/m.test(v)}function tryJson(v){const s=v.trim();if(!(s.startsWith("{")||s.startsWith("[")))return null;try{return JSON.parse(s)}catch{return null}}

function dedupeMessages(events){const out=[];for(const e of events){if((e.kind==="user"||e.kind==="assistant")&&e.content){let dup=false;for(let i=out.length-1;i>=0;i--){const p=out[i];if(p.kind==="assistant"&&e.kind==="user")break;if(p.kind==="user"&&e.kind==="assistant")break;if(p.kind===e.kind&&p.content===e.content){dup=true;break}}if(dup)continue}out.push(e)}return out}
